### ISSUE TITLE
Library fails to set pixel with any colour after the ninth used colour

### ISSUE THREAD

**Issue by LavenderTheGreat** [MartonDev/dpng#1]
This is the exact code I am using as of current to trigger the error:

```javascript
import { PNGImage } from 'https://deno.land/x/dpng/mod.ts'

let png = new PNGImage(16, 1)

let palette = [
    { r: 0, g: 248, b: 248, a: 1 },
    { r: 248, g: 248, b: 248, a: 1 },
    { r: 176, g: 176, b: 176, a: 1 },
    { r: 112, g: 112, b: 112, a: 1 },
    { r: 32, g: 32, b: 32, a: 1 },
    { r: 0, g: 152, b: 248, a: 1 },
    { r: 0, g: 64, b: 232, a: 1 },
    { r: 0, g: 32, b: 168, a: 1 },
    { r: 0, g: 0, b: 104, a: 1 },
    { r: 248, g: 248, b: 152, a: 1 },
    { r: 248, g: 168, b: 80, a: 1 },
    { r: 152, g: 80, b: 16, a: 1 },
    { r: 248, g: 32, b: 32, a: 1 },
    { r: 160, g: 0, b: 0, a: 1 },
    { r: 248, g: 216, b: 0, a: 1 },
    { r: 0, g: 152, b: 0, a: 1 }
  ]

for (let i=0; i < 16; i++ ){
    let colour2 = png.createRGBColor(palette[i])
    png.setPixel(i, 0, colour2)
}

Deno.writeFileSync('./bug.png', png.getBuffer())
```

The colours used are irrelevant, however it always stops on the 10th colour. The launch parameters I am using are as follows:

```
deno run --allow-net --allow-write bugtest.js
```

Anywho the expected output is that we get an array of 16 colours, however instead we get just 9, then the rest are transparent.

**Comment by martonlederer** [comment]
I'm sorry to hear that, however, I can't really help. This is a ported library, the base source is very old and unmaintained. I am not updating this anymore, because it would need a complete recode to work normally.

You could maybe try out this (https://nest.land/package/jpeg.ts) library, it looks promising

**Comment by LavenderTheGreat** [comment]
Aha, will look into it thanks!
